# Generated by Django 3.1.7 on 2021-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cv_experience_formation_hobby_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='sector',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
