# Generated by Django 3.1.7 on 2021-03-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cv_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='content',
        ),
    ]
