# Generated by Django 3.1.7 on 2021-03-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_skill_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='title',
            new_name='name',
        ),
    ]
