# Generated by Django 3.1.7 on 2021-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210312_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='formation',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
